import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Link from 'next/link'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id='homeImage'>
        <div className="App">
          <div className='homeContainer'>
            <div className='headerText'>
              <h1 className='ukName'>Prof. Dr. Ulrich Kaiser</h1>
              <h2 className='hmtmFunctions'>Musiktheorie / OER / Multimedia</h2>
              <h2 className='hmtm'>Hochschule für Musik und Theater München</h2>
            </div>
            <div className='homeImageContainer'>
              <img id="homeImage" src="/home.svg"></img>
              <div className='homeGrid'>
                <div className='_d1 box'>
                  <Link className='window' href='/'>Lehre</Link>
                </div>
                <div className='_11 box'>
                  <Link className='window' href='/wissenschaft/articles'>Wissenschaft</Link>
                </div>
                <div className='_12 box'>
                  <Link className='window' href='/'>Publikationen</Link>
                </div>
                <div className='_21 box'>
                  <Link className='window' href='/'>Projekte</Link>
                </div>
                <div className='_22 box'>
                  <Link className='window' href='/'>Vita</Link>
                </div>
                <div className='_31 box'>
                  <Link className='window' href='/'>Gesang</Link>
                </div>
                <div className='_32 box'>
                  <Link className='window' href='/'>Chorleitung</Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
